labels = [
    "Meeting Overload",
    "Meeting Shortage / Lack of Coordination",
    "Unnecessary Meetings or Tasks",
    "Desire for More Collaboration",
    "Fair Workload Distribution",
    "Unfair Workload Distribution",
    "Easy Access to Management",
    "Hard to Access Management",
    "Comfortable Sharing Feedback",
    "Uncomfortable Sharing Feedback",
    "Scheduling Needs Met",
    "Scheduling Needs Not Met",
    "PTO Respected",
    "PTO Not Respected",
    "No Issues Reported",
    
    "Work Interferes with Personal Life",
    "Good Separation Between Work and Home",
    "Positive Home Impact from Work",
    "Negative Home Impact from Work",
    "Sufficient Breaks",
    "Insufficient Breaks",
    "Has Remote/Hybrid Work",
    "No Remote/Hybrid Work",
    "Engaged in Virtual Meetings",
    "Disengaged in Virtual Meetings",
    "Feels Heard by Management",
    "Does Not Feel Heard by Management",
    "Timely Management Responses",
    "Slow Management Responses",
    "Frequently Seeks Help",
    "Rarely Seeks Help",
    
    "Positive Virtual Meeting Experience",
    "Negative Virtual Meeting Experience",
    "Desire for Meeting Improvements",
    "Satisfied with Meeting Quality",
    "Management is Responsive Remotely",
    "Management is Unresponsive Remotely",
    "Positive Remote/Hybrid Experience Overall",
    "Negative Remote/Hybrid Experience Overall",
    
    "Positive Feedback About Company",
    "Negative Feedback About Company",
    "Suggestions for Improvement",
    "Praise for Colleagues or Teams",
    "Process or Policy Concerns",
    "Resource or Tool Requests",
    "Training or Development Needs",
    "Other / Miscellaneous Feedback"
]

labelsLite = [
    "Too Many Meetings",
    "Too Few Meetings",
    "Unnecessary Tasks",
    "Want More Collaboration",
    "Workload Fairness",
    "Manager Accessible / Feedback OK",
    "Work Interferes with Life",
    "Good Work-Life Balance",
    "Enough Breaks",
    "Remote / Hybrid Setup",
    "Engaged in Meetings",
    "Management Responsive",
    "Positive Remote Experience",
    "Negative Remote Experience",
    "Want Meeting Improvements",
    "Positive Company Feedback",
    "Negative Company Feedback",
    "Improvement Suggestions",
    "Praise Colleagues / Teams",
    "Resource or Training Needs",
]